# Generated by Django 5.2.1 on 2025-05-25 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_alter_cases_id_us'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cases',
            name='test_status',
            field=models.BooleanField(verbose_name='Test Status'),
        ),
    ]
