# Generated by Django 5.2.1 on 2025-05-25 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0004_alter_cases_actual_result_alter_cases_test_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cases',
            options={'ordering': ['id'], 'verbose_name': 'Test Case', 'verbose_name_plural': 'Test Cases'},
        ),
    ]
