# Generated by Django 5.2.1 on 2025-05-25 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('histories', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='histories',
            options={'ordering': ['id'], 'verbose_name': 'Historia de Usuario', 'verbose_name_plural': 'Historias de Usuario'},
        ),
    ]
