# Generated by Django 5.2.1 on 2025-05-25 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rol',
            field=models.CharField(choices=[('admin', 'Admin'), ('user', 'User')], default='admin', max_length=10, verbose_name='Rol'),
        ),
    ]
